export const MAX_LEVEL = 100;

export const LIST_ELEMENT_INFO = new Map([
    ["FIRE", { baseAttack: 3.0, baseGold: 30, baseHealth: -6 }],
    ["WIND", { baseAttack: 1.8, baseGold: 20, baseHealth: -2 }],
    ["EARTH", { baseAttack: -1.8, baseGold: 30, baseHealth: 14 }],
    ["WATER", { baseAttack: 0, baseGold: 0, baseHealth: 10 }],
    ["PLANT", { baseAttack: 1.2, baseGold: 60, baseHealth: 8 }],
    ["METAL", { baseAttack: -1.8, baseGold: 75, baseHealth: 16 }],
    ["ENERGY", { baseAttack: 5.4, baseGold: 100, baseHealth: -8 }],
    ["VOID", { baseAttack: 2.4, baseGold: 140, baseHealth: 6 }],
    ["LIGHT", { baseAttack: 3.0, baseGold: 180, baseHealth: 8 }],
    ["SHADOW", { baseAttack: 6.0, baseGold: 180, baseHealth: -6 }],
    ["LEGENDARY", { baseAttack: 12.0, baseGold: 200, baseHealth: 40 }],
    ["DIVINE", { baseAttack: 13.8, baseGold: 220, baseHealth: 42 }],
    ["ANCIENT", { baseAttack: 1, baseGold: 220, baseHealth: 1 }]
])

export const LIST_EXCEPT_ATTACK_DRAGONS = new Map([
    ["Artoba", 89],
    ["Ashkelon", 86],
    ["Atlas", 178],
    ["Baha'jir", 90],
    ["Chrono Apep", 75],
    ["Chrono Aphrodite", 89],
    ["Chrono Isis", 88],
    ["Chrono Loki", 88],
    ["Chrono Nezha", 88],
    ["Chrono Odin", 88],
    ["Chrono Osiris", 88],
    ["Chrono Pangu", 88],
    ["Chrono Poseidon", 88],
    ["Chrono Seth", 88],
    ["Chrono Zeus", 88],
    ["Fall", 81],
    ["Freyja", 89],
    ["Hathor", 88],
    ["Ho'mala", 86],
    ["Ik'ez", 86],
    ["Koth'ez", 90],
    ["Laser", 81],
    ["Luzra", 86],
    ["Lysk", 90],
    ["Molim", 89],
    ["Momo'tu", 89],
    ["Mr. Popsicle", 204],
    ["Odin", 86],
    ["Oi'ra", 89],
    ["Oyar", 90],
    ["Pokra", 89],
    ["Ra", 86],
    ["Ribbon", 82],
    ["River", 74],
    ["Solden", 89],
    ["Ultimate Chronos", 88],
    ["Valkov", 89],
    ["Void", 62],
    ["Yamad", 74],
    ["Zephujin", 89],
]);

export const LIST_EXCEPT_HEALTH_DRAGONS = new Map([
    ["Artoba", 289],
    ["Ashkelon", 286],
    ["Atlas", 864],
    ["Baha'jir", 290],
    ["Chrono Apep", 260],
    ["Chrono Aphrodite", 289],
    ["Chrono Isis", 289],
    ["Chrono Loki", 228],
    ["Chrono Nezha", 289],
    ["Chrono Odin", 289],
    ["Chrono Osiris", 266],
    ["Chrono Pangu", 266],
    ["Chrono Poseidon", 289],
    ["Chrono Seth", 250],
    ["Chrono Zeus", 252],
    ["Fall", 243],
    ["Freyja", 288],
    ["Hathor", 288],
    ["Ho'mala", 286],
    ["Ik'ez", 286],
    ["Koth'ez", 290],
    ["Laser", 210],
    ["Luzra", 286],
    ["Lysk", 290],
    ["Molim", 289],
    ["Momo'tu", 289],
    ["Mr. Popsicle", 832],
    ["Odin", 245],
    ["Oi'ra", 289],
    ["Oyar", 290],
    ["Pokra", 289],
    ["Ra", 244],
    ["Ribbon", 243],
    ["River", 256],
    ["Solden", 289],
    ["Ultimate Chronos", 289],
    ["Valkov", 289],
    ["Void", 206],
    ["Yamad", 274],
    ["Zephujin", 289],
]);

export const LIST_BASE_GOLD_BY_TYPE = new Map([
    ["COMMON", 0],
    ["UNCOMMON", 10],
    ["RARE", 70],
    ["EPIC", 120],
    ["LEGENDARY", 270],
    ["DIVINE", 370],
    ["ANCIENT", 370],
]);